### Creamos nuevo usuarios

POST http://localhost:7777/api/v1/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJscmFtaXJleiIsInJvbGVzIjpbIkNSRUFSX1VTVUFSSU8iXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY2NjcyNjAxOH0.Bub49o57NHVIFq5-3-f9n6PvaaIz3U4xuRCKS0d1nlQ

{
  "user_name": "admin",
  "password" : "123456"

}

### Consultamos el usuario authenticado
GET http://localhost:7777/api/v1/user/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJscmFtaXJleiIsInJvbGVzIjpbIkNSRUFSX1VTVUFSSU8iXSwiaXNzIjoidWNiIiwicmVmcmVzaCI6ZmFsc2UsImV4cCI6MTY2Nzk2MTAyN30.RfG54w8p2y5yFTi3K5Ysx6p0Kyai8afEX7VfLWECe4E